"""Feature plugin scaffolder.

Generates an inert plugin template for a feature that has a profile in
``config/features.json``::

    python scripts/new_feature_plugin.py EM010_Screenshots
    python scripts/new_feature_plugin.py --all

**Why a generator instead of committed templates.** Fourteen hand-written templates
would be fourteen near-identical files free to drift apart, and the sprint that asked
for them also forbids duplication. One generator keeps the shape in a single place: fix
the shape once and every future template is fixed.

Generated templates are **abstract** -- ``feature_summary`` is left unimplemented -- so
plugin discovery skips them and an unfinished template can never execute in a real
regression run. That is the safety property that makes committing templates acceptable
at all.

Never overwrites an existing file: a half-implemented plugin must not be silently
replaced by a blank one.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
PROFILES_PATH = REPOSITORY_ROOT / "config" / "features.json"
PLUGINS_ROOT = REPOSITORY_ROOT / "plugins"
_FEATURE_ID = re.compile(r"^EM\d{3}_[A-Za-z0-9]+$")

_TEMPLATE = '''"""{feature_id} -- {name} validation plugin.

**Template: not implemented.** Generated by ``scripts/new_feature_plugin.py``.

This class is deliberately **abstract** -- :meth:`feature_summary` is unimplemented --
so plugin discovery skips it and it cannot run in a regression until someone finishes
it. Implement ``feature_summary`` to activate it.

Feature verification status: **{status}**.
{status_guidance}

What the profile in ``config/features.json`` expects:

* configuration: {configuration}
* runtime components: {runtime}
* SQLite tables: {tables}
* log patterns: {log_patterns}
* APIs: {apis}
* dashboard pages: {dashboard}
* evidence: {evidence}

Inherited from :class:`plugins.base.FeatureValidationPlugin`: profile loading, pipeline
composition, cross-layer correlation, evidence-sufficiency checking, summary building,
and the ``EM000_EnvironmentValidator`` dependency. Override only what this feature
genuinely needs.
"""

from __future__ import annotations

from abc import abstractmethod
from typing import Any, Mapping, Sequence

from framework.core.correlation import Correlation
from framework.shared.interfaces import Collector, Validator
from framework.shared.models import Evidence, ValidationContext
from plugins.base import FeatureValidationPlugin

__all__ = ["{class_name}"]


class {class_name}(FeatureValidationPlugin):
    """Validates the EmpMonitor {name} feature.

    Inherits every default from :class:`~plugins.base.FeatureValidationPlugin`. The
    hooks below are the intended extension points; each one currently defers to the
    generic behaviour.
    """

    feature_id = "{feature_id}"

    def collectors(self) -> Sequence[Collector]:
        """Collectors this feature needs.

        The inherited default is derived from the feature profile and reuses the
        framework's existing collectors. Add a collector here only if this feature
        needs an observation no existing collector makes -- and register it in the
        Evidence Catalog first.

        Returns:
            The collectors to run.
        """
        return super().collectors()

    def validators(self) -> Sequence[Validator]:
        """Validators this feature needs.

        Add feature-specific validators here. Prefer the generic validators in
        :mod:`framework.validators.generic`, supplying this feature's expectations from
        its profile, over writing new ones.

        Returns:
            The validators to run.
        """
        return super().validators()

    def correlate(
        self, context: ValidationContext, evidence: Sequence[Evidence]
    ) -> Sequence[Correlation]:
        """Relate this feature's observations across layers.

        Add feature-specific cross-layer questions here using
        :class:`framework.core.correlation.FeatureCorrelationEngine`. Return
        correlations, never verdicts -- turning them into findings is the correlation
        validator's job.

        Returns:
            The correlations.
        """
        return super().correlate(context, evidence)

    @abstractmethod
    def feature_summary(self) -> Mapping[str, Any]:
        """Return detail specific to {name}.

        **Implement this to activate the plugin.** It is re-declared abstract here on
        purpose: that is what keeps this class abstract, so plugin discovery skips it
        and an unfinished plugin cannot run in a regression. Remove the decorator and
        return real detail to activate it.

        Returns:
            Feature-specific detail for the report.

        Raises:
            NotImplementedError: Always, until implemented.
        """
        raise NotImplementedError(
            "{feature_id} is a generated template. Implement feature_summary() to "
            "activate it, and update its profile in config/features.json as evidence "
            "is gathered."
        )
'''

_GUIDANCE = {
    "Verified": (
        "The mechanism has been directly observed, so an expected artifact being absent\n"
        "is a real defect and this plugin may report ``FAILED``."
    ),
    "Partially Verified": (
        "Supporting artifacts have been observed but the feature's operation has not.\n"
        "Absence must be reported ``INCONCLUSIVE``, not ``FAILED`` -- see\n"
        "``FeatureProfile.absence_verdict``."
    ),
    "Hypothesis": (
        "Nothing about this feature's mechanism has been observed. Reverse-engineer it\n"
        "before validating it, and report absence as ``INCONCLUSIVE``: the framework does\n"
        "not yet know what absence means for this feature."
    ),
}


def load_profiles() -> dict[str, dict]:
    """Load the feature profiles.

    Returns:
        Profiles keyed by feature id.

    Raises:
        SystemExit: If the profile file is missing or malformed.
    """
    try:
        payload = json.loads(PROFILES_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise SystemExit(f"cannot read {PROFILES_PATH}: {exc}") from exc
    return {
        str(entry["feature_id"]): entry
        for entry in payload.get("profiles", [])
        if entry.get("feature_id")
    }


def _render(profile: dict) -> str:
    """Render the template for one profile.

    Args:
        profile: The feature profile.

    Returns:
        The module source.
    """
    feature_id = profile["feature_id"]
    status = profile.get("verification_status", "Hypothesis")

    def listing(key: str) -> str:
        values = profile.get(key) or []
        # Backslashes appear in real configuration keys and would become invalid
        # escape sequences inside the generated docstring.
        return (
            ", ".join(str(item).replace("\\", "\\\\") for item in values)
            if values
            else "none recorded"
        )

    return _TEMPLATE.format(
        feature_id=feature_id,
        name=profile.get("name", feature_id),
        class_name=f"{feature_id.split('_', 1)[1]}Plugin",
        status=status,
        status_guidance=_GUIDANCE.get(status, ""),
        configuration=listing("required_configuration"),
        runtime=listing("expected_runtime_components"),
        tables=listing("expected_sqlite_tables"),
        log_patterns=listing("expected_log_patterns"),
        apis=listing("expected_apis"),
        dashboard=listing("expected_dashboard_pages") + " (unobserved: no dashboard collector)",
        evidence=listing("expected_evidence"),
    )


def generate(feature_id: str, profiles: dict[str, dict], *, force: bool = False) -> str:
    """Generate one template.

    Args:
        feature_id: Feature to scaffold.
        profiles: Loaded profiles.
        force: Overwrite an existing file.

    Returns:
        A one-line status message.
    """
    if not _FEATURE_ID.match(feature_id):
        return f"SKIP  {feature_id}: not of the form EM<NNN>_<Name>"
    if feature_id not in profiles:
        return (
            f"SKIP  {feature_id}: no profile in config/features.json -- add the profile "
            "first, so the plugin's expectations are recorded before its code exists"
        )

    package = PLUGINS_ROOT / feature_id
    module = package / "plugin.py"
    if module.exists() and not force:
        return f"KEEP  {feature_id}: {module.relative_to(REPOSITORY_ROOT)} already exists"

    package.mkdir(parents=True, exist_ok=True)
    profile = profiles[feature_id]
    class_name = f"{feature_id.split('_', 1)[1]}Plugin"
    module.write_text(_render(profile), encoding="utf-8")
    (package / "__init__.py").write_text(
        f'"""{feature_id} -- {profile.get("name", feature_id)}.\n\n'
        "Generated template. The plugin class is abstract until ``feature_summary`` is\n"
        "implemented, so plugin discovery skips it and it cannot run in a regression.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"from plugins.{feature_id}.plugin import {class_name}\n\n"
        f'__all__ = ["{class_name}"]\n',
        encoding="utf-8",
    )
    return f"NEW   {feature_id}: {module.relative_to(REPOSITORY_ROOT)}"


def main(argv: list[str] | None = None) -> int:
    """Run the scaffolder.

    Args:
        argv: Argument list.

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(description="Scaffold a feature plugin template.")
    parser.add_argument("feature_id", nargs="?", help="e.g. EM010_Screenshots")
    parser.add_argument("--all", action="store_true", help="scaffold every profiled feature")
    parser.add_argument("--force", action="store_true", help="overwrite an existing template")
    args = parser.parse_args(argv)

    profiles = load_profiles()
    if not args.all and not args.feature_id:
        parser.error("give a feature id or --all")

    targets = sorted(profiles) if args.all else [args.feature_id]
    for target in targets:
        print(generate(target, profiles, force=args.force))
    return 0


if __name__ == "__main__":
    sys.exit(main())
