"""EM017_ApplicationUsage -- Application Usage validation plugin.

**Template: not implemented.** Generated by ``scripts/new_feature_plugin.py``.

This class is deliberately **abstract** -- :meth:`feature_summary` is unimplemented --
so plugin discovery skips it and it cannot run in a regression until someone finishes
it. Implement ``feature_summary`` to activate it.

Feature verification status: **Partially Verified**.
Supporting artifacts have been observed but the feature's operation has not.
Absence must be reported ``INCONCLUSIVE``, not ``FAILED`` -- see
``FeatureProfile.absence_verdict``.

What the profile in ``config/features.json`` expects:

* configuration: none recorded
* runtime components: empmonitor.exe
* SQLite tables: usagedata6, pending_usagedata6
* log patterns: config_refresh
* APIs: add-activity
* dashboard pages: reports (unobserved: no dashboard collector)
* evidence: EV-001, EV-002, EV-003, EV-007, EV-011

Inherited from :class:`plugins.base.FeatureValidationPlugin`: profile loading, pipeline
composition, cross-layer correlation, evidence-sufficiency checking, summary building,
and the ``EM000_EnvironmentValidator`` dependency. Override only what this feature
genuinely needs.
"""

from __future__ import annotations

from typing import Any, Mapping, Sequence

from framework.core.correlation import Correlation
from framework.shared.interfaces import Collector, Validator
from framework.shared.models import Evidence, ValidationContext
from plugins.base import FeatureValidationPlugin

__all__ = ["ApplicationUsagePlugin"]


class ApplicationUsagePlugin(FeatureValidationPlugin):
    """Validates the EmpMonitor Application Usage feature.

    Inherits every default from :class:`~plugins.base.FeatureValidationPlugin`. The
    hooks below are the intended extension points; each one currently defers to the
    generic behaviour.
    """

    feature_id = "EM017_ApplicationUsage"

    def collectors(self) -> Sequence[Collector]:
        """Collectors this feature needs.

        The inherited default is derived from the feature profile and reuses the
        framework's existing collectors. Add a collector here only if this feature
        needs an observation no existing collector makes -- and register it in the
        Evidence Catalog first.

        Returns:
            The collectors to run.
        """
        return super().collectors()

    def validators(self) -> Sequence[Validator]:
        """Validators this feature needs.

        Add feature-specific validators here. Prefer the generic validators in
        :mod:`framework.validators.generic`, supplying this feature's expectations from
        its profile, over writing new ones.

        Returns:
            The validators to run.
        """
        return super().validators()

    def correlate(
        self, context: ValidationContext, evidence: Sequence[Evidence]
    ) -> Sequence[Correlation]:
        """Relate this feature's observations across layers.

        Add feature-specific cross-layer questions here using
        :class:`framework.core.correlation.FeatureCorrelationEngine`. Return
        correlations, never verdicts -- turning them into findings is the correlation
        validator's job.

        Returns:
            The correlations.
        """
        return super().correlate(context, evidence)

    def feature_summary(self) -> Mapping[str, Any]:
        """Return detail specific to Application Usage.

        Returns:
            Feature-specific detail for the report.
        """
        profile = self.profile
        return {
            "feature_id": self.feature_id,
            "feature_name": profile.name,
            "status": profile.verification_status,
            "expected_tables": list(profile.expected_sqlite_tables),
            "expected_runtime_components": list(profile.expected_runtime_components),
            "expected_log_patterns": list(profile.expected_log_patterns),
            "expected_apis": list(profile.expected_apis),
        }
