import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://app.dev.empmonitor.com/amember/member")
    page.get_by_role("textbox", name="Username/Email").click()
    page.get_by_role("textbox", name="Username/Email").fill("qt_dev")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("qt_developers")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("link", name="Total Enrollments").click()
    page.get_by_role("searchbox", name="Search:").click()
    page.get_by_role("link", name="Aftab k").click()
    page.get_by_role("link", name="Edit").click()
    page.get_by_role("textbox", name="Email Address").click()
    page.locator(".btn.btn-default.fas.fa-eye.toggle-password-show-edit").click()
    page.get_by_role("textbox", name="Password", exact=True).click()
    page.locator("div:nth-child(2) > div:nth-child(12)").click()
    page.locator("#ShiftfilterEdit").select_option("1177")
    page.get_by_role("button", name="Update").click()
    page.get_by_role("button", name="OK").click()
    page.get_by_role("link", name="Settings", exact=True).click()
    page.get_by_text("Visible").click()
    page.locator("#KeyStrokeRadio1").check()
    page.locator("#EmailMonitoringRadio1").check()
    page.locator("input[name=\"WebsiteOption\"]").first.check()
    page.locator("input[name=\"ScreenshotsOption\"]").first.check()
    page.locator("input[name=\"videoOption\"]").first.check()
    page.get_by_role("row", name="Screen Recording With Voice").get_by_label("Enable").check()
    page.locator("#ScreenCast1").check()
    page.locator("#clipboard_detection_enable").check()
    page.get_by_role("button", name="On Off").first.click()
    page.get_by_role("link", name="Unlimited").click()
    page.get_by_role("button", name="Save").click()
    page.get_by_role("link", name="Employee Full Details").click()
    page.get_by_role("link", name=" Timesheets", description="Timesheets", exact=True).click()
    page.get_by_role("gridcell", name="No Time Sheets data found !").click()
    page.get_by_role("columnheader", name="Clock In: activate to sort").click()
    page.get_by_role("columnheader", name="Clock Out: activate to sort").click()
    page.get_by_text("-08-01 - 2026-08-01").first.click()
    page.get_by_text("Last 7 Days").click()
    page.get_by_text("Last 30 Days").click()
    page.get_by_role("gridcell", name="-07-2026 12:25:01").click()
    page.get_by_role("gridcell", name="-07-2026 19:37:36").click()
    page.get_by_role("gridcell", name=":12:35").click()
    page.locator("td").filter(has_text=re.compile(r"^07:03:35$")).click()
    page.get_by_role("gridcell", name=":03:35").nth(1).click()
    page.get_by_role("gridcell", name=":34:09").click()
    page.get_by_role("gridcell", name=":45:51").click()
    page.get_by_role("gridcell", name=":45:51").click()
    page.get_by_role("gridcell", name=":43:35").click()
    page.get_by_role("gridcell", name=":00:00").first.click()
    page.get_by_role("gridcell", name=":09:00").click()
    page.get_by_role("link", name=" Screenshots").click()
    page.get_by_role("textbox", name="Select Date").click()
    page.get_by_title("Prev", exact=True).click()
    page.get_by_role("link", name="30").click()
    page.get_by_role("link", name=" Timesheets", description="Timesheets", exact=True).click()
    page.get_by_role("link", name=" Screenshots").click()
    page.get_by_role("textbox", name="Select Date").click()
    page.get_by_role("link", name="23").click()
    page.get_by_role("button", description="Search", exact=True).click()
    page.locator("#fromTime").select_option("15:00")
    page.get_by_role("button", description="Search", exact=True).click()
    page.locator("#fromTime").select_option("06:00")
    page.get_by_role("button", description="Search", exact=True).click()
    page.get_by_text("No screenshots present for").click()
    page.get_by_role("link", name=" Screen Recording").click()
    page.get_by_role("button", name=" Search").click()
    page.get_by_text("No screen records present for").click()
    page.get_by_role("link", name=" Screen Cast").click()
    page.get_by_role("button", name="Connect").click()
    page.locator("#canvas-img-default").click(position={"x":346,"y":55})
    page.get_by_role("link", name=" Web History").click()
    page.get_by_role("cell", name=" chatgpt.com").click()
    page.get_by_role("cell", name=" docs.google.com").click()
    page.get_by_role("link", name=" App History").click()
    page.get_by_text("Top Application Usage").click()
    page.get_by_text("Top Application Usage").click()
    page.get_by_role("cell", name=" telegram desktop").click()
    page.get_by_role("cell", name=" virtual machine connection").click()
    page.get_by_role("link", name=" Key Strokes").click()
    page.get_by_role("gridcell", name="telegram desktop").first.click()
    page.get_by_role("gridcell", name="admin dashboard me thy havent").click()
    page.get_by_role("gridcell", name="app.dev.empmonitor.com").click()
    page.get_by_role("gridcell", name="Application").first.click()
    page.get_by_role("gridcell", name="Application").first.click()
    page.get_by_role("gridcell", name="telegram desktop").first.click()
    page.get_by_role("gridcell", name="admin dashboard me thy havent").click()
    page.get_by_role("link", name="Home").click()
    page.get_by_role("link", name="Currently Active").click()
    page.get_by_role("button", name="×").click()
    page.get_by_role("link", name="Absent").click()
    page.get_by_role("searchbox", name="Search:").click()
    page.get_by_role("button", name="×").click()
    page.get_by_role("link", name="Employee ").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
