import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page.goto("https://app.dev.empmonitor.com/amember/member")
    page.get_by_role("textbox", name="Username/Email").fill("qt_dev")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("link", name="Employee ").click()
    page.get_by_role("link", name="Employee-Details").click()
    page.get_by_role("textbox", name="Search").click()
    page.get_by_role("textbox", name="Search").fill("suman")
    page.get_by_role("textbox", name="Search").press("Enter")
    page.locator("#SearchButton").click()
    page.get_by_role("gridcell", name="SumanTest USB").click()
    page.get_by_role("gridcell", name="sumanusbtest456@gmail.com").click()
    page.locator("#lo45008").click()
    page.locator("#dpt45008").click()
    page.get_by_role("row", name="SumanTest USB sumanusbtest456").locator("[id=\"dpt' + id + '\"]").click()
    page.locator("#ro45008").click()
    page.locator("#ro45008").click()
    page.get_by_role("columnheader", name="Role : activate to sort").click()
    page.get_by_role("gridcell", name="7654433").click()
    page.get_by_label("Emp-Code : activate to sort").get_by_text("Emp-Code").click()
    page.locator("#sa45007").click()
    page.get_by_text("OS", exact=True).click()
    page.get_by_role("gridcell", name="-07-2026 16:53:00").click()
    page.get_by_role("gridcell", name="DESKTOP-C5H42NG").click()
    page.get_by_label("Computer Name : activate to").get_by_text("Computer Name").click()
    page.get_by_role("columnheader", name="version : activate to sort").click()
    page.locator("#sv45007").click()
    page.get_by_role("button", name="Register Employee").click()
    page.get_by_role("textbox", name="Enter First Name").click()
    page.get_by_role("textbox", name="Enter First Name").fill("auto")
    page.get_by_role("textbox", name="Enter First Name").press("Tab")
    page.get_by_role("textbox", name="Last Name *").fill("test")
    page.get_by_role("textbox", name="Last Name *").press("Tab")
    page.get_by_role("textbox", name="Email Address * Email Address").fill("autotest@gmail.com")
    page.get_by_role("textbox", name="Email Address * Email Address").press("Tab")
    page.get_by_role("textbox", name="Password *", exact=True).fill("Pass@123")
    page.get_by_role("textbox", name="Password *", exact=True).press("Tab")
    page.get_by_role("textbox", name="Confirm Password * Employee").fill("Pass@123")
    page.get_by_role("textbox", name="Employee Code", exact=True).click()
    page.get_by_role("textbox", name="Employee Code", exact=True).fill("sdadasd")
    page.locator("#locations-addEmp").select_option("hrms")
    page.locator("#EmpReg_departments").select_option("Default")
    page.locator("#emp-register").get_by_role("list").click()
    page.locator("#select2-role-addEmp-result-ol5a-1510").click()
    page.locator("#timeZoneAppend").select_option("(UTC +05:30) Kolkata, Asia")
    page.locator("#Shiftfilteradd").select_option("1159")
    page.locator("#empReg").click()
    page.get_by_role("button", name="OK").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
